#!/bin/python3

import math
import os
import random
import re
import sys


# Read the integer input
n = int(input())

# Check for conditions
if n % 2 != 0:  # If the number is odd
    print("Weird")
elif n % 2 == 0:  # If the number is even
    if 2 <= n <= 5:
        print("Not Weird")
    elif 6 <= n <= 20:
        print("Weird")
    elif n > 20:
        print("Not Weird")
